### PR TITLE
Block thumbnail creation if no width is set

### PR DESCRIPTION
**Pull request by jrschreiber**
When using e.g. `(image: 01.png)` a thumbnail is beeing generated even if the image already is scaled down. In my opinion the plugin should only create a thumbnail if a `width` is set — as written in the description of your plugins.

Sincerely,
John

### CODE REVIEW

**Comment by julien-gargot** [comment]
Hi John!

Thank you for the feedback!

You’re right, there is a problem with the code and I think I did not write the Readme correctly :)
Purpose of the plugin *is* to generate a thumbnail in all case. Even if editor does not add a `width` option in the markdown. That why there are options to set in the configuration file.

But, to satisfy most of use, plugin should generate the thumb without `width` options in the markdown only if `kirbytext.image.width` or `kirbytext.image.height` is set in the configuration file.
Does this sound good to you?

**Comment by jrschreiber** [comment]
Hello!

That is indeed a good idea. Or you change the README, if this was your initial purpose. :)

Well, I now use the plugin with the slight change I made ... just wanted to give my thoughts. I'm happy I quickly found your thumb customization built on top of the standard image tag!

For the _site-to-be-created_'s purpose I found it helpful to change the code further: a thumb should only be created if a `width` of a image is set — or if `kirbytext.image.width` can be found in the configuration (I don't like to hard code the thumb width into the tag) **and** the image doesn't exceed a specific width.
But maybe that's another story :)

Greetings,
Johan

**Comment by julien-gargot** [comment]
I’ll try do make the first changes soon.
Add a break point beyond which the image is generated is a good idea. I put it on the roadmap!

**Comment by jrschreiber** [comment]
Cool. Thank you!

**Comment by julien-gargot** [comment]
First update online ;)

**Comment by jrschreiber** [comment]
I took a look into it — awesome!

**Pull request closed without merging**
